set_property SRC_FILE_INFO {cfile:/home/ecelrc/students/cjanecka/EE316L/Lab4/Lab4_PartB/Lab4_PartB.srcs/constrs_1/new/edge_constrs.xdc rfile:../../../Lab4_PartB.srcs/constrs_1/new/edge_constrs.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {sw}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {led}]
